version: '2'
services:
    p04-app:
        image: p04
        external_links:
            - p04-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/p04?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    p04-mysql:
        extends:
            file: mysql.yml
            service: p04-mysql
