version: '2'
services:
    p04-mysql:
        container_name: p04-mysql
        image: mysql:5.7.14
        # volumes:
        #     - ~/volumes/jhipster/p04/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=p04
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
